-- Active: 1675088471994@@127.0.0.1@3306@my_blog
CREATE TABLE category (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL
);


CREATE TABLE country (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(20) NOT NULL
);


CREATE TABLE article (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(20) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  summary TEXT,
  description LONGTEXT NOT NULL,
  image_src VARCHAR(255),
  image_alt VARCHAR(255),
  rating INT NOT NULL DEFAULT(1),
  is_archived BOOLEAN DEFAULT(false),
  visit_duration TIME NOT NULL,
  country_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE category_by_article (
  article_id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE ON UPDATE NO ACTION
);


